"""Core domain abstractions, AST definitions, serialization, enums, and protocols."""

from __future__ import annotations

from typing import Final

from .ast import (
    ActionNode,
    BaseAction,
    CvTriggerAction,
    DelayAction,
    KeyboardKeyAction,
    LoopContainerAction,
    MacroSequence,
    MouseButtonAction,
    MouseMoveAction,
    MouseScrollAction,
)
from .enums import (
    ActionType,
    ButtonState,
    ExecutionState,
    KeyState,
    MouseButton,
    TriggerComparison,
)
from .exceptions import (
    ExecutionAbortedError,
    ExecutionError,
    FrameCaptureError,
    HookInstallationError,
    HookStarvationError,
    InputSynthesisError,
    MacroSuiteError,
    MacroTimeoutError,
    PlatformError,
    SchemaVersionMismatchError,
    SerializationError,
    TemplateMatchError,
    TimerResolutionError,
    VisionError,
)
from .serialization import (
    CURRENT_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    MacroSerializer,
    load_macro_file,
    macro_from_json,
    macro_from_yaml,
    macro_to_json,
    macro_to_yaml,
    save_macro_file,
)
from .types import (
    CancellationTokenProtocol,
    ExecutionTelemetryCallback,
    FrameCaptureProtocol,
    ImageBuffer,
    InputHookProtocol,
    InputSynthesizerProtocol,
    KeyboardHookCallback,
    MatchResult,
    Microseconds,
    Milliseconds,
    MouseHookCallback,
    Nanoseconds,
    NormalizedPoint2D,
    Point2D,
    RawKeyboardEvent,
    RawMouseEvent,
    Rect2D,
    Size2D,
)

__all__: Final[list[str]] = [
    # AST Models & Discriminator Union
    "ActionNode",
    "BaseAction",
    "CvTriggerAction",
    "DelayAction",
    "KeyboardKeyAction",
    "LoopContainerAction",
    "MacroSequence",
    "MouseButtonAction",
    "MouseMoveAction",
    "MouseScrollAction",
    # Domain Enums
    "ActionType",
    "ButtonState",
    "ExecutionState",
    "KeyState",
    "MouseButton",
    "TriggerComparison",
    # Domain Exceptions
    "ExecutionAbortedError",
    "ExecutionError",
    "FrameCaptureError",
    "HookInstallationError",
    "HookStarvationError",
    "InputSynthesisError",
    "MacroSuiteError",
    "MacroTimeoutError",
    "PlatformError",
    "SchemaVersionMismatchError",
    "SerializationError",
    "TemplateMatchError",
    "TimerResolutionError",
    "VisionError",
    # Serialization Facade & Helpers
    "CURRENT_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "MacroSerializer",
    "load_macro_file",
    "macro_from_json",
    "macro_from_yaml",
    "macro_to_json",
    "macro_to_yaml",
    "save_macro_file",
    # Type Aliases & Runtime Protocols
    "CancellationTokenProtocol",
    "ExecutionTelemetryCallback",
    "FrameCaptureProtocol",
    "ImageBuffer",
    "InputHookProtocol",
    "InputSynthesizerProtocol",
    "KeyboardHookCallback",
    "MatchResult",
    "Microseconds",
    "Milliseconds",
    "MouseHookCallback",
    "Nanoseconds",
    "NormalizedPoint2D",
    "Point2D",
    "RawKeyboardEvent",
    "RawMouseEvent",
    "Rect2D",
    "Size2D",
]